// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: proto/queue-bridge.proto

package queuebridgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueBridgeBalancer_Push_FullMethodName      = "/queuebridge.QueueBridgeBalancer/Push"
	QueueBridgeBalancer_PushBatch_FullMethodName = "/queuebridge.QueueBridgeBalancer/PushBatch"
)

// QueueBridgeBalancerClient is the client API for QueueBridgeBalancer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueBridgeBalancerClient interface {
	Push(ctx context.Context, in *QueueMessage, opts ...grpc.CallOption) (*EmptyResponse, error)
	PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type queueBridgeBalancerClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueBridgeBalancerClient(cc grpc.ClientConnInterface) QueueBridgeBalancerClient {
	return &queueBridgeBalancerClient{cc}
}

func (c *queueBridgeBalancerClient) Push(ctx context.Context, in *QueueMessage, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, QueueBridgeBalancer_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueBridgeBalancerClient) PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, QueueBridgeBalancer_PushBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueBridgeBalancerServer is the server API for QueueBridgeBalancer service.
// All implementations must embed UnimplementedQueueBridgeBalancerServer
// for forward compatibility.
type QueueBridgeBalancerServer interface {
	Push(context.Context, *QueueMessage) (*EmptyResponse, error)
	PushBatch(context.Context, *PushBatchRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedQueueBridgeBalancerServer()
}

// UnimplementedQueueBridgeBalancerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueBridgeBalancerServer struct{}

func (UnimplementedQueueBridgeBalancerServer) Push(context.Context, *QueueMessage) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedQueueBridgeBalancerServer) PushBatch(context.Context, *PushBatchRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushBatch not implemented")
}
func (UnimplementedQueueBridgeBalancerServer) mustEmbedUnimplementedQueueBridgeBalancerServer() {}
func (UnimplementedQueueBridgeBalancerServer) testEmbeddedByValue()                             {}

// UnsafeQueueBridgeBalancerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueBridgeBalancerServer will
// result in compilation errors.
type UnsafeQueueBridgeBalancerServer interface {
	mustEmbedUnimplementedQueueBridgeBalancerServer()
}

func RegisterQueueBridgeBalancerServer(s grpc.ServiceRegistrar, srv QueueBridgeBalancerServer) {
	// If the following call pancis, it indicates UnimplementedQueueBridgeBalancerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueBridgeBalancer_ServiceDesc, srv)
}

func _QueueBridgeBalancer_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueBridgeBalancerServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueBridgeBalancer_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueBridgeBalancerServer).Push(ctx, req.(*QueueMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueBridgeBalancer_PushBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueBridgeBalancerServer).PushBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueBridgeBalancer_PushBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueBridgeBalancerServer).PushBatch(ctx, req.(*PushBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueBridgeBalancer_ServiceDesc is the grpc.ServiceDesc for QueueBridgeBalancer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueBridgeBalancer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "queuebridge.QueueBridgeBalancer",
	HandlerType: (*QueueBridgeBalancerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _QueueBridgeBalancer_Push_Handler,
		},
		{
			MethodName: "PushBatch",
			Handler:    _QueueBridgeBalancer_PushBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/queue-bridge.proto",
}
